version: '3'
services:
  wapp-backend:
    container_name: wapp-backend
    build: ./wapp-backend
    volumes:
      - './wapp-backend:/app'
    ports:
      - '8000:8000'
    command: >
      python -c "manage.py migrate && manage.py createsuperuser && manage.py runserver --host 0.0.0.0 --port 8000"

  wapp-frontend:
    container_name: wapp-frontend
    build: ./wapp-frontend
    volumes:
      - './wapp-frontend:/app'
    ports:
      - '4200:80'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - wapp-backend

  web_server:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "80:80"
    # volumes:
    #   - "./src:/usr/share/nginx/html"
    #   - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - wapp-frontend
