version: '3'
services:
  wapp-backend:
    container_name: wapp-backend
    build:
      context: ./wapp-backend
      args:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./wapp-backend:/app
    ports:
      - '9091:9091'
    expose:
      - 9091
    command:
      python manage.py runserver 0.0.0.0:9091
    restart: always

  wapp-frontend:
    container_name: wapp-frontend
    build:
      context: ./wapp-frontend
      args:
        PRODUCTION_URL: ${PRODUCTION_URL}
    volumes:
      - ./wapp-frontend:/app
    ports:
      - '9090:9090'
    restart: always