version: '3'
services:
  wapp-backend:
    container_name: wapp-backend
    build:
      context: ./wapp-backend
      # args:
      #   DATABASE_NAME: ${DATABASE_NAME}
      #   DATABASE_USER: ${DATABASE_USER}
      #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      #   DATABASE_HOST: ${DATABASE_HOST}
      #   DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./wapp-backend:/app
    ports:
      - '8000:8000'
    command:
      python manage.py runserver 0.0.0.0:8000

  wapp-frontend:
    container_name: wapp-frontend
    build: ./wapp-frontend
    volumes:
      - ./wapp-frontend:/usr/src/app
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  # web_server:
  #   image: nginx:alpine
  #   container_name: web_server
  #   ports:
  #     - "80:80"
  #   # volumes:
  #   #   - "./src:/usr/share/nginx/html"
  #   #   - "./nginx.conf:/etc/nginx/nginx.conf"
  #   depends_on:
  #     - wapp-frontend
