# Generated by Django 3.0.5 on 2020-04-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('value', models.FloatField(editable=False, max_length=10, verbose_name='сумма')),
                ('currency', models.CharField(default='₽', max_length=10, verbose_name='валюта')),
            ],
        ),
        migrations.CreateModel(
            name='SubtractTransaction',
            fields=[
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата')),
                ('value', models.FloatField(max_length=10, null=True, verbose_name='сумма')),
                ('commentary', models.TextField(max_length=120, null=True, verbose_name='комментарий')),
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('wallet_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subtransaction', to='wallet_app.Wallet', verbose_name='кошелек')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата')),
                ('value', models.FloatField(max_length=10, null=True, verbose_name='сумма')),
                ('commentary', models.TextField(max_length=120, null=True, verbose_name='комментарий')),
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('wallet_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addtransaction', to='wallet_app.Wallet', verbose_name='кошелек')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
