# Generated by Django 3.0.5 on 2020-04-09 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addtransaction',
            name='value',
            field=models.FloatField(default=0, max_length=10, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='addtransaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtransaction', to='wallet_app.Wallet', verbose_name='кошелек'),
        ),
        migrations.AlterField(
            model_name='subtracttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtracttransaction',
            name='value',
            field=models.FloatField(default=0, max_length=10, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='subtracttransaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtransaction', to='wallet_app.Wallet', verbose_name='кошелек'),
        ),
    ]
