# Generated by Django 3.0.5 on 2020-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_auto_20200409_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtransaction',
            name='post_trans_value',
            field=models.FloatField(default=None, editable=False, null=True, verbose_name='значение после транзакции'),
        ),
        migrations.AddField(
            model_name='subtracttransaction',
            name='post_trans_value',
            field=models.FloatField(default=None, editable=False, null=True, verbose_name='значение после транзакции'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='value',
            field=models.FloatField(default=0, editable=False, max_length=10, verbose_name='сумма'),
        ),
    ]
