# Generated by Django 3.0.5 on 2020-04-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_auto_20200409_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtransaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_transactions', to='wallet_app.Wallet', verbose_name='кошелек'),
        ),
        migrations.AlterField(
            model_name='subtracttransaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_transactions', to='wallet_app.Wallet', verbose_name='кошелек'),
        ),
    ]
