# Generated by Django 3.0.5 on 2020-04-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_auto_20200413_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата')),
                ('value', models.FloatField(default=0, max_length=10, verbose_name='сумма')),
                ('commentary', models.TextField(default=None, max_length=120, null=True, verbose_name='комментарий')),
                ('id', models.CharField(default='t664be28c0e9845669e4a8525d71fac6f', editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Tra', max_length=3, verbose_name='тип транзакции')),
                ('post_trans_value', models.FloatField(default=None, editable=False, null=True, verbose_name='значение после транзакции')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='wallet_app.Wallet', verbose_name='кошелек')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='subtracttransaction',
            name='wallet_id',
        ),
        migrations.DeleteModel(
            name='AddTransaction',
        ),
        migrations.DeleteModel(
            name='SubtractTransaction',
        ),
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet_app.transaction',),
        ),
        migrations.CreateModel(
            name='SubtractTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet_app.transaction',),
        ),
    ]
