# Generated by Django 3.0.5 on 2020-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0006_auto_20200414_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default='t263759c91b024983a1eabf5807f61dec', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
