# Generated by Django 3.0.5 on 2020-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0007_auto_20200414_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commentary',
            field=models.TextField(default='', max_length=120, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default='bf43fda7635f4ef3a4f49a7ea0fb482c', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='', max_length=3, null=True, verbose_name='тип транзакции'),
        ),
    ]
